// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SVM.Models;

#nullable disable

namespace SVM.Migrations
{
    [DbContext(typeof(SvmContext))]
    partial class SvmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SVM.Models.AdmissionInquiry", b =>
                {
                    b.Property<int>("InquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inquiry_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InquiryId"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("class_name");

                    b.Property<DateTime?>("InquiryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("inquiry_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message");

                    b.Property<string>("ParentName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("parent_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("StudentName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("student_name");

                    b.HasKey("InquiryId")
                        .HasName("PK__admissio__A1FB453A6383C8BA");

                    b.ToTable("admission_inquiry", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("class_name");

                    b.Property<string>("Medium")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("medium");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.HasKey("ClassId")
                        .HasName("PK__classes__FDF47986108B795B");

                    b.HasIndex("SessionId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("SVM.Models.FeePayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<int?>("FeeId")
                        .HasColumnType("int")
                        .HasColumnName("fee_id");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_mode");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__fee_paym__ED1FC9EA5DCAEF64");

                    b.HasIndex("FeeId");

                    b.HasIndex("StudentId");

                    b.ToTable("fee_payment", (string)null);
                });

            modelBuilder.Entity("SVM.Models.FeeStructure", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("FeeType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fee_type");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_amount");

                    b.HasKey("FeeId")
                        .HasName("PK__fee_stru__A19C8AFB5812160E");

                    b.HasIndex("ClassId");

                    b.HasIndex("SectionId");

                    b.ToTable("fee_structure", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Groupmaster", b =>
                {
                    b.Property<int>("GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("g_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GId"));

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_name");

                    b.HasKey("GId")
                        .HasName("PK__groupmas__49FB61C47F60ED59");

                    b.ToTable("groupmaster", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("SectionName")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("section_name");

                    b.HasKey("SectionId")
                        .HasName("PK__sections__F842676A46E78A0C");

                    b.HasIndex("ClassId");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateOnly?>("EndDate")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("IsActive")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("session_name");

                    b.Property<DateOnly?>("StartDate")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("SessionId")
                        .HasName("PK__sessions__69B13FDC0CBAE877");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Designation")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_id");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Qualification")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("qualification");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("salary");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("StaffId")
                        .HasName("PK__staff__1963DD9C07F6335A");

                    b.HasIndex("UserId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("SVM.Models.StaffAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<TimeOnly?>("CheckinTime")
                        .HasColumnType("time")
                        .HasColumnName("checkin_time");

                    b.Property<TimeOnly?>("CheckoutTime")
                        .HasColumnType("time")
                        .HasColumnName("checkout_time");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__staff_at__3213E83F2F10007B");

                    b.HasIndex("StaffId");

                    b.ToTable("staff_attendance", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("AadharNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("aadhar_no");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("AdmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("admission_date");

                    b.Property<string>("AdmissionNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("admission_no");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("blood_group");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("father_name");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<int?>("Grno")
                        .HasColumnType("int")
                        .HasColumnName("GRNO");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MotherPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mother_phone");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pincode");

                    b.Property<string>("PreviousSchool")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("previous_school");

                    b.Property<int?>("RollNo")
                        .HasColumnType("int")
                        .HasColumnName("roll_no");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("StudentId")
                        .HasName("PK__students__2A33069A4BAC3F29");

                    b.HasIndex("ClassId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SVM.Models.StudentAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__student___3213E83F534D60F1");

                    b.HasIndex("StudentId");

                    b.ToTable("student_attendance", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subject_name");

                    b.HasKey("SubjectId")
                        .HasName("PK__subjects__5004F66015502E78");

                    b.HasIndex("ClassId");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("SVM.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("PK__teacher___3213E83F1A14E395");

                    b.HasIndex("ClassId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StaffId");

                    b.HasIndex("SubjectId");

                    b.ToTable("teacher_subject", (string)null);
                });

            modelBuilder.Entity("SVM.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_photo");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F03317E3D");

                    b.HasIndex("GroupId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SVM.Models.Class", b =>
                {
                    b.HasOne("SVM.Models.Session", "Session")
                        .WithMany("Classes")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK__classes__session__1273C1CD");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SVM.Models.FeePayment", b =>
                {
                    b.HasOne("SVM.Models.FeeStructure", "Fee")
                        .WithMany("FeePayments")
                        .HasForeignKey("FeeId")
                        .HasConstraintName("FK__fee_payme__fee_i__60A75C0F");

                    b.HasOne("SVM.Models.Student", "Student")
                        .WithMany("FeePayments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__fee_payme__stude__5FB337D6");

                    b.Navigation("Fee");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SVM.Models.FeeStructure", b =>
                {
                    b.HasOne("SVM.Models.Class", "Class")
                        .WithMany("FeeStructures")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__fee_struc__class__59FA5E80");

                    b.HasOne("SVM.Models.Section", "Section")
                        .WithMany("FeeStructures")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK__fee_struc__secti__5AEE82B9");

                    b.Navigation("Class");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SVM.Models.Section", b =>
                {
                    b.HasOne("SVM.Models.Class", "Class")
                        .WithMany("Sections")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__sections__class___48CFD27E");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SVM.Models.Staff", b =>
                {
                    b.HasOne("SVM.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__staff__user_id__09DE7BCC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SVM.Models.StaffAttendance", b =>
                {
                    b.HasOne("SVM.Models.Staff", "Staff")
                        .WithMany("StaffAttendances")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__staff_att__staff__30F848ED");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SVM.Models.Student", b =>
                {
                    b.HasOne("SVM.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__students__class___4E88ABD4");

                    b.HasOne("SVM.Models.Section", "Section")
                        .WithMany("Students")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK__students__sectio__4F7CD00D");

                    b.HasOne("SVM.Models.Session", "Session")
                        .WithMany("Students")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK__students__sessio__5070F446");

                    b.HasOne("SVM.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__students__user_i__4D94879B");

                    b.Navigation("Class");

                    b.Navigation("Section");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SVM.Models.StudentAttendance", b =>
                {
                    b.HasOne("SVM.Models.Student", "Student")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__student_a__stude__5535A963");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SVM.Models.Subject", b =>
                {
                    b.HasOne("SVM.Models.Class", "Class")
                        .WithMany("Subjects")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__subjects__class___173876EA");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SVM.Models.TeacherSubject", b =>
                {
                    b.HasOne("SVM.Models.Class", "Class")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__teacher_s__class__1DE57479");

                    b.HasOne("SVM.Models.Session", "Session")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK__teacher_s__sessi__1ED998B2");

                    b.HasOne("SVM.Models.Staff", "Staff")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__teacher_s__staff__1BFD2C07");

                    b.HasOne("SVM.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__teacher_s__subje__1CF15040");

                    b.Navigation("Class");

                    b.Navigation("Session");

                    b.Navigation("Staff");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SVM.Models.User", b =>
                {
                    b.HasOne("SVM.Models.Groupmaster", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__users__group_id__0519C6AF");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SVM.Models.Class", b =>
                {
                    b.Navigation("FeeStructures");

                    b.Navigation("Sections");

                    b.Navigation("Students");

                    b.Navigation("Subjects");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SVM.Models.FeeStructure", b =>
                {
                    b.Navigation("FeePayments");
                });

            modelBuilder.Entity("SVM.Models.Groupmaster", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SVM.Models.Section", b =>
                {
                    b.Navigation("FeeStructures");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SVM.Models.Session", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SVM.Models.Staff", b =>
                {
                    b.Navigation("StaffAttendances");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SVM.Models.Student", b =>
                {
                    b.Navigation("FeePayments");

                    b.Navigation("StudentAttendances");
                });

            modelBuilder.Entity("SVM.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SVM.Models.User", b =>
                {
                    b.Navigation("Staff");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
